batch_size: 256
checkpoints_path: "checkpoints"
clip_grad_norm: 4.0
data_path: "data/nle_data"
db_path: "ttyrecs.db"
env: "NetHackScore-v0-ttyimg-bot-v0"
eval_episodes_per_seed: 1
eval_every: 10000
eval_seeds: 50
group: "ChaoticBC"
learning_rate: 0.001
n_workers: 16
name: "ChaoticBC"
project: "NeuralNetHack"
rnn_hidden_dim: 512
rnn_layers: 1
seq_len: 32
train_seed: 42
update_steps: 180000
use_prev_action: true
version: "v0"
